### PR TITLE
Add binson class

### PR DESCRIPTION
**Pull request by AndreasHansson73**
Hi there!
I have  created a c++ class that wraps binson_c_light. Please have a look at it!

There is a small example of how to use it in the readme file. Please also look at utest/binson_class_test.cpp for a more complex example.

### CODE REVIEW

**Comment by AndreasHansson73** [comment]
@sijohans @ppmag  Could you please have a look!

**Comment by sijohans** [comment]
Looks really nice. Some thoughts:
perhaps binson_write_name_with_len could be used instead of binson_write_name in Binson::serializeItems()? I guess the length of the string is known so doing another strlen() in binson_write_name is not needed.

I've not worked a lot with the std libraries in c++. Is the map sorted by key value by default? The c library requires the user to know that field must be put in order. It would be nice if a higher level class would abstract that for one (this seems to be the case). To make sure that the serialized object is valid the function binson_writer_verify could be used. I tested a little bit:

```
diff --git a/binson.cpp b/binson.cpp
index 22270a2..d018423 100644
--- a/binson.cpp
+++ b/binson.cpp
@@ -106,7 +106,7 @@ bool Binson::seralizeItems(binson_writer *w) const
     bool result = true;
     for (auto &item: m_items)
     {
-        result = result && binson_write_name(w, item.first.c_str());
+        result = result && binson_write_name_with_len(w, item.first.c_str(), item.first.length());
         result = result && seralizeItem(w, item.second);
     }
     return result;
@@ -141,6 +141,7 @@ bool Binson::serialize(binson_writer *w) const
     result = result && binson_write_object_begin(w);
     result = result && seralizeItems(w);
     result = result && binson_write_object_end(w);
+    result = result && binson_writer_verify(&w);
     return result;
 }
 
diff --git a/utest/binson_class_test.cpp b/utest/binson_class_test.cpp
index 7822775..a0b45d8 100644
--- a/utest/binson_class_test.cpp
+++ b/utest/binson_class_test.cpp
@@ -185,11 +185,34 @@ TEST(binson_class_test1)
 
 }
 
+TEST(unsorted_writing)
+{
+    uint8_t buf[64];
+    binson_writer w;
+    binson_parser p;
+
+    Binson b;
+    b.put("a", 1);
+    b.put("c", 2);
+    b.put("b", 3);
+
+    binson_writer_init(&w, buf, sizeof(buf));
+    ASSERT_TRUE(b.serialize(&w));
+
+    binson_parser_init(&p, buf, binson_writer_get_counter(&w));
+    b.deserialize(&p);
+    ASSERT_TRUE(b.get("a").getInt() == 1);
+    ASSERT_TRUE(b.get("b").getInt() == 3);
+    ASSERT_TRUE(b.get("c").getInt() == 2);
+
+
+}
 
 /*======= Main function =====================================================*/
 
 int main(void) {
     RUN_TEST(binson_class_test1);
+    RUN_TEST(unsorted_writing);
     PRINT_RESULT();
 }
```

The binson_write_* functions will return the required number of bytes if the buffer is too small. I.e., the function **std::vector<uint8_t> Binson::serialize() const** does not have to guess the initial size and then resize it multiple times. See this test. https://github.com/assaabloy-ppi/binson-c-light/blob/master/utest/binson_writer_test.c#L103

**Comment by sijohans** [comment]
1. That's correct, the specification says lexicographical order.

Otherwise i think this is ok to merge. When we reviewed the binson-java library there was an attack on the java map class. If choosing "bad" field names that will causes a lot of collisions which could impact the performance. However, i don't know if this also affects c++ and in order to get slow performance, the binson object must be very large.

**Comment by AndreasHansson73** [comment]
@ppmag A common/similar API for different object oriented languages sounds like a good idea to me. Do we have an issue on this?

**Comment by ppmag** [comment]
@AndreasHansson73 ,
We have no issue on this yet,  it looks like inter-repo issue, but let's have related issue open in this repo for now.   I'll open it.

**Pull request merged**
